[2023-06-14T13:01:50.599+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.create_table manual__2023-06-14T13:01:49.098615+00:00 [queued]>
[2023-06-14T13:01:50.609+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.create_table manual__2023-06-14T13:01:49.098615+00:00 [queued]>
[2023-06-14T13:01:50.610+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T13:01:50.610+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-14T13:01:50.611+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T13:01:50.630+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-14 13:01:49.098615+00:00
[2023-06-14T13:01:50.635+0000] {standard_task_runner.py:55} INFO - Started process 138 to run task
[2023-06-14T13:01:50.642+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_postgres', 'create_table', 'manual__2023-06-14T13:01:49.098615+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/postgress_db.py', '--cfg-path', '/tmp/tmp2j3fu9bg']
[2023-06-14T13:01:50.643+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask create_table
[2023-06-14T13:01:50.712+0000] {task_command.py:388} INFO - Running <TaskInstance: database_postgres.create_table manual__2023-06-14T13:01:49.098615+00:00 [running]> on host 73219206ba7b
[2023-06-14T13:01:50.773+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=database_postgres
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T13:01:49.098615+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T13:01:49.098615+00:00
[2023-06-14T13:01:50.774+0000] {sql.py:254} INFO - Executing: CREATE TABLE IF NOT EXISTS my_table (
  id INT UNIQUE NOT NULL,
  current_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
[2023-06-14T13:01:50.794+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-06-14T13:01:50.798+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=database_postgres, task_id=create_table, execution_date=20230614T130149, start_date=20230614T130150, end_date=20230614T130150
[2023-06-14T13:01:50.807+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task create_table (The conn_id `postgres` isn't defined; 138)
[2023-06-14T13:01:50.820+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-14T13:01:50.843+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
